openapi: 3.0.0
info:
  title: Flask User Management API
  description: API for user registration, updating user information, and user authentication.
  version: 1.0.0

servers:
  - url: http://localhost:5001
    description: Local Flask server

paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
              - username
              - password
      responses:
        '200':
          description: User successfully registered
        '404':
          description: Missing login or password
        '400':
          description: User already exist

  /update:
    put:
      summary: Update user information
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                first_name:
                  type: string
                last_name:
                  type: string
                date_of_birth:
                  type: string
                email:
                  type: string
                phone_number:
                  type: string
              required:
              - token
      responses:
        '200':
          description: User information successfully updated
        '400':
          description: Token is missing
        '401':
          description: Invalid token

  /authenticate:
    post:
      summary: Authenticate user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
              - username
              - password
      responses:
        '200':
          description: User authenticated successfully
        '401':
          description: User does not exist or password is wrong
        '404':
          description: Missing login or password
