@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(person, "Пользователь", "Пользователь приложения")

System(system, "Приложение - трекер задач")

Rel(person, system, "Отслеживает задачи")

@enduml