@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.1.0
!includeurl ICONURL/common.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!include DEVICONS/angular.puml
!include DEVICONS/python.puml
!include DEVICONS/database.puml
!include ICONURL/dev2/postgresql.puml

!define SPRITESURL https://raw.githubusercontent.com/plantuml-stdlib/gilbarbara-plantuml-sprites/v1.1/sprites
!includeurl SPRITESURL/rabbitmq.puml

Person(person, "Пользователь", "Пользователь приложения")

Container(frontend, "Трекер задач","Angular", "Frontend для работы с приложением", "angular")
Container(backend, "Трекер задач backend", "Python", "Главный сервис, отвечает также за аутентификацию/регистрацию", "python")

Container(statistics_service, "Сервис статистик", "Python", "Сервис статистики для подсчета комментариев и просмотров", "python")
Container(tasks_service, "Сервис задач", "Python", "Отслеживает задачи и комментарии", "python")

Container(statistics_database, "База данных для статистки", "Clickhouse", "Хранит информацию о статистике", "database")
Container(users_database, "База данных для хранения информации о пользователях", "PostreSQL", "Хранит информацию о пользователях", "postgresql")
Container(tasks_database, "База данных для хранения информации о задачах", "PostreSQL", "Хранит информацию о задчах", "postgresql")
Container(message_broker, "Брокер сообщений", "rabbitMQ", "Передаёт статистику о комментариях и просмотрах", "rabbitmq")



Rel(person, frontend, "Отслеживает задачи")
Rel(frontend, backend, "Вызов методов", "REST")
Rel(backend, statistics_service, "Запрос статистики", "gRPC")
Rel(backend, tasks_service, "Обновление задач", "gRPC")
Rel(backend, users_database, "Сохраняет информацию о пользователях")
Rel(statistics_service, statistics_database, "Сохраняет статистику")
Rel(tasks_service, tasks_database, "Сохраняет информацию о задачах")
Rel(tasks_service, message_broker, "Отправляет статистику о задачах")
Rel(message_broker, statistics_service, "Отправляет статистику о задачах")

SHOW_LEGEND()


@enduml