# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tasks.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btasks.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x99\x01\n\x04Task\x12\x0e\n\x06userId\x18\x01 \x01(\x04\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x32\n\x0e\x64\x61teOfCreation\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x64\x65\x61\x64line\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06status\x18\x05 \x01(\x04\"\x1d\n\x05Tasks\x12\x14\n\x05tasks\x18\x01 \x03(\x0b\x32\x05.Task\"-\n\nTaskWithId\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x13\n\x04task\x18\x02 \x01(\x0b\x32\x05.Task\"\'\n\tTaskShort\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0e\n\x06userId\x18\x02 \x01(\x04\":\n\nPagination\x12\x0e\n\x06offset\x18\x01 \x01(\x04\x12\x0c\n\x04size\x18\x02 \x01(\x04\x12\x0e\n\x06userId\x18\x03 \x01(\x04\"*\n\x0cTaskResponse\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0e\n\x06status\x18\x02 \x01(\t2\xd1\x01\n\x0bTaskManager\x12$\n\nCreateTask\x12\x05.Task\x1a\r.TaskResponse\"\x00\x12*\n\nUpdateTask\x12\x0b.TaskWithId\x1a\r.TaskResponse\"\x00\x12)\n\nDeleteTask\x12\n.TaskShort\x1a\r.TaskResponse\"\x00\x12!\n\x08GetTasks\x12\x0b.Pagination\x1a\x06.Tasks\"\x00\x12\"\n\x0bGetTaskById\x12\n.TaskShort\x1a\x05.Task\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tasks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASK']._serialized_start=49
  _globals['_TASK']._serialized_end=202
  _globals['_TASKS']._serialized_start=204
  _globals['_TASKS']._serialized_end=233
  _globals['_TASKWITHID']._serialized_start=235
  _globals['_TASKWITHID']._serialized_end=280
  _globals['_TASKSHORT']._serialized_start=282
  _globals['_TASKSHORT']._serialized_end=321
  _globals['_PAGINATION']._serialized_start=323
  _globals['_PAGINATION']._serialized_end=381
  _globals['_TASKRESPONSE']._serialized_start=383
  _globals['_TASKRESPONSE']._serialized_end=425
  _globals['_TASKMANAGER']._serialized_start=428
  _globals['_TASKMANAGER']._serialized_end=637
# @@protoc_insertion_point(module_scope)
