# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tasks_statistics.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16tasks_statistics.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x14\n\x06TaskId\x12\n\n\x02id\x18\x01 \x01(\x04\" \n\x0bTop5Request\x12\x11\n\tparameter\x18\x01 \x01(\t\"U\n\x16TaskStatisticsResponse\x12\n\n\x02id\x18\x01 \x01(\x04\x12\r\n\x05likes\x18\x02 \x01(\x04\x12\x10\n\x08\x63omments\x18\x03 \x01(\x04\x12\x0e\n\x06status\x18\x04 \x01(\t\"P\n\x16\x41rrayOfTasksStatistics\x12&\n\x05tasks\x18\x01 \x03(\x0b\x32\x17.TaskStatisticsResponse\x12\x0e\n\x06status\x18\x02 \x01(\t\"8\n\x12UserLikeStatistics\x12\x0e\n\x06userId\x18\x01 \x01(\x04\x12\x12\n\nlikesCount\x18\x02 \x01(\x04\"Z\n\x1b\x41rrayOfUsersLikesStatistics\x12+\n\x0euserStatistics\x18\x01 \x03(\x0b\x32\x13.UserLikeStatistics\x12\x0e\n\x06status\x18\x02 \x01(\t2\xcd\x01\n\x11StatisticsManager\x12\x37\n\x11GetTaskStatistics\x12\x07.TaskId\x1a\x17.TaskStatisticsResponse\"\x00\x12\x37\n\x0cGetTop5Tasks\x12\x0c.Top5Request\x1a\x17.ArrayOfTasksStatistics\"\x00\x12\x46\n\x0cGetTop3Users\x12\x16.google.protobuf.Empty\x1a\x1c.ArrayOfUsersLikesStatistics\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tasks_statistics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKID']._serialized_start=55
  _globals['_TASKID']._serialized_end=75
  _globals['_TOP5REQUEST']._serialized_start=77
  _globals['_TOP5REQUEST']._serialized_end=109
  _globals['_TASKSTATISTICSRESPONSE']._serialized_start=111
  _globals['_TASKSTATISTICSRESPONSE']._serialized_end=196
  _globals['_ARRAYOFTASKSSTATISTICS']._serialized_start=198
  _globals['_ARRAYOFTASKSSTATISTICS']._serialized_end=278
  _globals['_USERLIKESTATISTICS']._serialized_start=280
  _globals['_USERLIKESTATISTICS']._serialized_end=336
  _globals['_ARRAYOFUSERSLIKESSTATISTICS']._serialized_start=338
  _globals['_ARRAYOFUSERSLIKESSTATISTICS']._serialized_end=428
  _globals['_STATISTICSMANAGER']._serialized_start=431
  _globals['_STATISTICSMANAGER']._serialized_end=636
# @@protoc_insertion_point(module_scope)
